package com.google.android.gms.pay;

import com.google.android.gms.common.Feature;

/* JADX INFO: compiled from: com.google.android.gms:play-services-pay@@16.4.0 */
/* JADX INFO: loaded from: classes3.dex */
public final class zzn {
    public static final Feature zzA;
    public static final Feature zzB;
    public static final Feature zzC;
    public static final Feature zzD;
    public static final Feature zzE;
    public static final Feature zzF;
    public static final Feature zzG;
    public static final Feature zzH;
    public static final Feature zzI;
    public static final Feature zzJ;
    public static final Feature zzK;
    public static final Feature zzL;
    public static final Feature zzM;
    public static final Feature zzN;
    public static final Feature zzO;
    public static final Feature zzP;
    public static final Feature zzQ;
    public static final Feature zzR;
    public static final Feature zzS;
    public static final Feature zzT;
    public static final Feature zzU;
    public static final Feature zzV;
    public static final Feature zzW;
    public static final Feature zzX;
    public static final Feature zzY;
    public static final Feature zzZ;
    public static final Feature zza;
    public static final Feature zzaA;
    public static final Feature zzaB;
    public static final Feature[] zzaC;
    public static final Feature zzaa;
    public static final Feature zzab;
    public static final Feature zzac;
    public static final Feature zzad;
    public static final Feature zzae;
    public static final Feature zzaf;
    public static final Feature zzag;
    public static final Feature zzah;
    public static final Feature zzai;
    public static final Feature zzaj;
    public static final Feature zzak;
    public static final Feature zzal;
    public static final Feature zzam;
    public static final Feature zzan;
    public static final Feature zzao;
    public static final Feature zzap;
    public static final Feature zzaq;
    public static final Feature zzar;
    public static final Feature zzas;
    public static final Feature zzat;
    public static final Feature zzau;
    public static final Feature zzav;
    public static final Feature zzaw;
    public static final Feature zzax;
    public static final Feature zzay;
    public static final Feature zzaz;
    public static final Feature zzb;
    public static final Feature zzc;
    public static final Feature zzd;
    public static final Feature zze;
    public static final Feature zzf;
    public static final Feature zzg;
    public static final Feature zzh;
    public static final Feature zzi;
    public static final Feature zzj;
    public static final Feature zzk;
    public static final Feature zzl;
    public static final Feature zzm;
    public static final Feature zzn;
    public static final Feature zzo;
    public static final Feature zzp;
    public static final Feature zzq;
    public static final Feature zzr;
    public static final Feature zzs;
    public static final Feature zzt;
    public static final Feature zzu;
    public static final Feature zzv;
    public static final Feature zzw;
    public static final Feature zzx;
    public static final Feature zzy;
    public static final Feature zzz;

    /* JADX DEBUG: Don't trust debug lines info. Lines numbers was adjusted: min line is 1 */
    static {
        Feature feature = new Feature("pay", 10L);
        zza = feature;
        Feature feature2 = new Feature("pay_attestation_signal", 1L);
        zzb = feature2;
        Feature feature3 = new Feature("pay_pay_capabilities", 1L);
        zzc = feature3;
        Feature feature4 = new Feature("pay_feature_check", 1L);
        zzd = feature4;
        Feature feature5 = new Feature("pay_get_card_centric_bundle", 1L);
        zze = feature5;
        Feature feature6 = new Feature("pay_get_passes", 1L);
        zzf = feature6;
        Feature feature7 = new Feature("pay_get_pay_api_availability_status", 3L);
        zzg = feature7;
        Feature feature8 = new Feature("pay_get_se_prepaid_card", 1L);
        zzh = feature8;
        Feature feature9 = new Feature("pay_debit_se_prepaid_card", 1L);
        zzi = feature9;
        Feature feature10 = new Feature("pay_get_specific_bulletin", 1L);
        zzj = feature10;
        Feature feature11 = new Feature("pay_get_transit_cards", 1L);
        zzk = feature11;
        Feature feature12 = new Feature("pay_get_wallet_status", 1L);
        zzl = feature12;
        Feature feature13 = new Feature("pay_global_actions", 1L);
        zzm = feature13;
        Feature feature14 = new Feature("pay_gp3_support", 1L);
        zzn = feature14;
        Feature feature15 = new Feature("pay_homescreen_sorting", 3L);
        zzo = feature15;
        Feature feature16 = new Feature("pay_homescreen_bulletins", 2L);
        zzp = feature16;
        Feature feature17 = new Feature("pay_onboarding", 2L);
        zzq = feature17;
        Feature feature18 = new Feature("pay_mark_tos_accepted_for_partner", 1L);
        zzr = feature18;
        Feature feature19 = new Feature("pay_move_card_on_other_device", 1L);
        zzs = feature19;
        Feature feature20 = new Feature("pay_passes_field_update_notifications", 1L);
        zzt = feature20;
        Feature feature21 = new Feature("pay_passes_notifications", 2L);
        zzu = feature21;
        Feature feature22 = new Feature("pay_payment_method", 1L);
        zzv = feature22;
        Feature feature23 = new Feature("pay_payment_method_action_tokens", 2L);
        zzw = feature23;
        Feature feature24 = new Feature("pay_payment_method_server_action", 1L);
        zzx = feature24;
        Feature feature25 = new Feature("pay_provision_se_prepaid_card", 1L);
        zzy = feature25;
        Feature feature26 = new Feature("pay_request_module", 1L);
        zzz = feature26;
        Feature feature27 = new Feature("pay_reverse_purchase", 1L);
        zzA = feature27;
        Feature feature28 = new Feature("pay_save_passes", 5L);
        zzB = feature28;
        Feature feature29 = new Feature("pay_save_passes_jwt", 3L);
        zzC = feature29;
        Feature feature30 = new Feature("pay_save_purchased_card", 1L);
        zzD = feature30;
        Feature feature31 = new Feature("pay_sync_bundle", 2L);
        zzE = feature31;
        Feature feature32 = new Feature("pay_settings", 1L);
        zzF = feature32;
        Feature feature33 = new Feature("pay_topup_se_prepaid_card", 1L);
        zzG = feature33;
        Feature feature34 = new Feature("pay_list_commuter_pass_renewal_options_for_se_prepaid_card", 1L);
        zzH = feature34;
        Feature feature35 = new Feature("pay_transactions", 6L);
        zzI = feature35;
        Feature feature36 = new Feature("pay_sync_transaction_by_id", 1L);
        zzJ = feature36;
        Feature feature37 = new Feature("pay_update_bundle_with_client_settings", 1L);
        zzK = feature37;
        Feature feature38 = new Feature("pay_clock_skew_millis", 1L);
        zzL = feature38;
        Feature feature39 = new Feature("pay_set_se_transit_default_status", 1L);
        zzM = feature39;
        Feature feature40 = new Feature("pay_se_postpaid_transactions", 1L);
        zzN = feature40;
        Feature feature41 = new Feature("pay_se_prepaid_transactions", 1L);
        zzO = feature41;
        Feature feature42 = new Feature("pay_get_clock_skew_millis", 1L);
        zzP = feature42;
        Feature feature43 = new Feature("pay_renew_commuter_pass_for_se_prepaid_card", 1L);
        zzQ = feature43;
        Feature feature44 = new Feature("pay_remove_se_postpaid_token", 1L);
        zzR = feature44;
        Feature feature45 = new Feature("pay_change_se_postpaid_default_status", 1L);
        zzS = feature45;
        Feature feature46 = new Feature("pay_wear_payment_methods", 2L);
        zzT = feature46;
        Feature feature47 = new Feature("pay_wear_closed_loop_cards", 1L);
        zzU = feature47;
        Feature feature48 = new Feature("pay_perform_wear_operation", 1L);
        zzV = feature48;
        Feature feature49 = new Feature("pay_delete_se_prepaid_card", 1L);
        zzW = feature49;
        Feature feature50 = new Feature("pay_transit_issuer_tos", 1L);
        zzX = feature50;
        Feature feature51 = new Feature("pay_get_se_mfi_prepaid_cards", 1L);
        zzY = feature51;
        Feature feature52 = new Feature("pay_get_last_user_present_timestamp", 1L);
        zzZ = feature52;
        Feature feature53 = new Feature("pay_mdoc", 7L);
        zzaa = feature53;
        Feature feature54 = new Feature("pay_get_se_feature_readiness_status", 1L);
        zzab = feature54;
        Feature feature55 = new Feature("pay_recover_se_card", 1L);
        zzac = feature55;
        Feature feature56 = new Feature("pay_set_logging_session_id", 1L);
        zzad = feature56;
        Feature feature57 = new Feature("pay_set_wallet_item_surfacing", 2L);
        zzae = feature57;
        Feature feature58 = new Feature("pay_set_se_transit_default", 1L);
        zzaf = feature58;
        Feature feature59 = new Feature("pay_get_wallet_bulletins", 2L);
        zzag = feature59;
        Feature feature60 = new Feature("pay_mse_operation", 1L);
        zzah = feature60;
        Feature feature61 = new Feature("pay_clear_bulletin_interaction_for_dev", 1L);
        zzai = feature61;
        Feature feature62 = new Feature("pay_get_pending_intent_for_wallet_on_wear", 2L);
        zzaj = feature62;
        Feature feature63 = new Feature("pay_get_predefined_rotating_barcode_values", 1L);
        zzak = feature63;
        Feature feature64 = new Feature("pay_get_mdl_refresh_timestamps", 1L);
        zzal = feature64;
        Feature feature65 = new Feature("pay_store_mdl_refresh_timestamp", 1L);
        zzam = feature65;
        Feature feature66 = new Feature("pay_perform_id_card_operation", 1L);
        zzan = feature66;
        Feature feature67 = new Feature("pay_block_closed_loop_cards", 1L);
        zzao = feature67;
        Feature feature68 = new Feature("pay_delete_data_for_tests", 1L);
        zzap = feature68;
        Feature feature69 = new Feature("pay_perform_closed_loop_operation", 1L);
        zzaq = feature69;
        Feature feature70 = new Feature("pay_get_callouts", 1L);
        zzar = feature70;
        Feature feature71 = new Feature("pay_perform_gw4_operation", 1L);
        zzas = feature71;
        Feature feature72 = new Feature("pay_get_mdoc_credential_pending_intent", 1L);
        zzat = feature72;
        Feature feature73 = new Feature("pay_get_images_for_valuable", 1L);
        zzau = feature73;
        Feature feature74 = new Feature("pay_save_images_for_valuable", 1L);
        zzav = feature74;
        Feature feature75 = new Feature("pay_notify_card_tap_event", 1L);
        zzaw = feature75;
        Feature feature76 = new Feature("pay_perform_emoney_card_operation", 1L);
        zzax = feature76;
        Feature feature77 = new Feature("pay_check_readiness_for_emoney", 1L);
        zzay = feature77;
        Feature feature78 = new Feature("pay_push_emoney_card", 1L);
        zzaz = feature78;
        Feature feature79 = new Feature("pay_notify_emoney_card_status_update", 1L);
        zzaA = feature79;
        Feature feature80 = new Feature("pay_perform_pix_operation", 1L);
        zzaB = feature80;
        zzaC = new Feature[]{feature, feature2, feature3, feature4, feature5, feature6, feature7, feature8, feature9, feature10, feature11, feature12, feature13, feature14, feature15, feature16, feature17, feature18, feature19, feature20, feature21, feature22, feature23, feature24, feature25, feature26, feature27, feature28, feature29, feature30, feature31, feature32, feature33, feature34, feature35, feature36, feature37, feature38, feature39, feature40, feature41, feature42, feature43, feature44, feature45, feature46, feature47, feature48, feature49, feature50, feature51, feature52, feature53, feature54, feature55, feature56, feature57, feature58, feature59, feature60, feature61, feature62, feature63, feature64, feature65, feature66, feature67, feature68, feature69, feature70, feature71, feature72, feature73, feature74, feature75, feature76, feature77, feature78, feature79, feature80};
    }
}
